-- ============================================================
-- Special Event deal seeds — auto-generated by scripts/generateEventSeeds.mjs
-- Generated: 2026-09-05T20:02:49.351Z
-- Solver: embedded JS fallback
-- Positions are row-major: position 1 = top-left, gridSize² = bottom-right.
-- Deal numbers are event-sequential across pages (page 1 with 4 deals owns 1-4, page 2 starts at 5).
-- Paste into: Supabase Dashboard > SQL Editor > Run
-- ============================================================

-- Event: swedish-midsommar-2026 (Swedish Midsommar 2026)
insert into special_events (id, title, description, starts_at, game_kind, sort_order)
values ('swedish-midsommar-2026', 'Swedish Midsommar 2026', 'Swedish Midsommar 2026 marks the traditional Midsummer celebration with maypoles, floral crowns, outdoor dances, and gatherings under the long Nordic summer light around the solstice.', '2026-06-19T00:00:00Z', 'draw-1', 1);

insert into special_event_pages (event_id, page_number, grid_size, image_path, coin_reward)
values
  ('swedish-midsommar-2026', 1, 2, 'swedish-midsommar-2026/page1.jpg', 50),
  ('swedish-midsommar-2026', 2, 3, 'swedish-midsommar-2026/page2.jpg', 100);

-- Page 1 (2×2 = 4 deals), positions 1..4 row-major, deals 1..4 event-sequential:
insert into special_event_deals (page_id, "position", seed, deal_number)
select id, unnest(array[1,2,3,4]), unnest(array[3017581129,3017581132,3017581133,3017581134]::bigint[]), unnest(array[1,2,3,4])
  from special_event_pages
  where event_id = 'swedish-midsommar-2026' and page_number = 1;

-- Page 2 (3×3 = 9 deals), positions 1..9 row-major, deals 5..13 event-sequential:
insert into special_event_deals (page_id, "position", seed, deal_number)
select id, unnest(array[1,2,3,4,5,6,7,8,9]), unnest(array[555354599,555354597,555354596,555354601,555354594,555354593,555354605,555354591,555354590]::bigint[]), unnest(array[5,6,7,8,9,10,11,12,13])
  from special_event_pages
  where event_id = 'swedish-midsommar-2026' and page_number = 2;

