-- ============================================================
-- Special Event deal seeds — auto-generated by scripts/generateEventSeeds.mjs
-- Generated: 2026-09-05T05:24:38.061Z
-- Solver: embedded JS fallback
-- Positions are row-major: position 1 = top-left, gridSize² = bottom-right.
-- Paste into: Supabase Dashboard > SQL Editor > Run
-- ============================================================

-- Event: festival-of-san-fermin-2026 (Festival of San Fermín 2026)
insert into special_events (id, title, description, starts_at, game_kind, sort_order)
values ('festival-of-san-fermin-2026', 'Festival of San Fermín 2026', 'The 2026 Festival of San Fermín in Pamplona, Spain, features the famous running of the bulls, traditional processions, and festive gatherings from 6 to 14 July.', '2026-07-06T00:00:00Z', 'draw-1', 1);

insert into special_event_pages (event_id, page_number, grid_size, image_path, coin_reward)
values
  ('festival-of-san-fermin-2026', 1, 2, 'festival-of-san-fermin-2026/page1.jpg', 40),
  ('festival-of-san-fermin-2026', 2, 3, 'festival-of-san-fermin-2026/page2.jpg', 90),
  ('festival-of-san-fermin-2026', 3, 2, 'festival-of-san-fermin-2026/page3.jpg', 40);

insert into special_event_deals (page_id, "position", seed)
select id, unnest(array[1,2,3,4]), unnest(array[2264386537,2264386535,2264386538,2264386539]::bigint[])
  from special_event_pages
  where event_id = 'festival-of-san-fermin-2026' and page_number = 1;

insert into special_event_deals (page_id, "position", seed)
select id, unnest(array[1,2,3,4,5,6,7,8,9]), unnest(array[2036550390,2036550391,2036550388,2036550393,2036550387,2036550394,2036550386,2036550395,2036550384]::bigint[])
  from special_event_pages
  where event_id = 'festival-of-san-fermin-2026' and page_number = 2;

insert into special_event_deals (page_id, "position", seed)
select id, unnest(array[1,2,3,4]), unnest(array[508310301,508310305,508310299,508310306]::bigint[])
  from special_event_pages
  where event_id = 'festival-of-san-fermin-2026' and page_number = 3;

-- Event: holi-2026 (Holi 2026)
insert into special_events (id, title, description, starts_at, game_kind, sort_order)
values ('holi-2026', 'Holi 2026', 'Holi 2026, the Festival of Colors, marks the arrival of spring in India and beyond with joyful gatherings, vibrant powdered dyes, music, and the triumph of good over evil.', '2026-03-04T00:00:00Z', 'draw-1', 1);

insert into special_event_pages (event_id, page_number, grid_size, image_path, coin_reward)
values
  ('holi-2026', 1, 4, 'holi-2026/page1.jpg', 160),
  ('holi-2026', 2, 3, 'holi-2026/page2.jpg', 90);

insert into special_event_deals (page_id, "position", seed)
select id, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]), unnest(array[3598821088,3598821087,3598821094,3598821095,3598821096,3598821097,3598821083,3598821098,3598821082,3598821099,3598821081,3598821100,3598821080,3598821101,3598821079,3598821102]::bigint[])
  from special_event_pages
  where event_id = 'holi-2026' and page_number = 1;

insert into special_event_deals (page_id, "position", seed)
select id, unnest(array[1,2,3,4,5,6,7,8,9]), unnest(array[986276554,986276555,986276553,986276556,986276552,986276550,986276559,986276549,986276548]::bigint[])
  from special_event_pages
  where event_id = 'holi-2026' and page_number = 2;

-- Event: diwali-2026 (Diwali 2026)
insert into special_events (id, title, description, starts_at, game_kind, sort_order)
values ('diwali-2026', 'Diwali 2026', 'Diwali 2026, the Festival of Lights, celebrates the victory of light over darkness with oil lamps, rangoli patterns, family gatherings, and fireworks across India and the global diaspora.', '2026-11-08T00:00:00Z', 'draw-1', 1);

insert into special_event_pages (event_id, page_number, grid_size, image_path, coin_reward)
values
  ('diwali-2026', 1, 3, 'diwali-2026/page1.jpg', 90),
  ('diwali-2026', 2, 2, 'diwali-2026/page2.jpg', 40),
  ('diwali-2026', 3, 2, 'diwali-2026/page3.jpg', 40);

-- Page 1 (3×3 = 9 deals), positions 1..9 row-major:
insert into special_event_deals (page_id, "position", seed)
select id, unnest(array[1,2,3,4,5,6,7,8,9]), unnest(array[3132712544,3132712545,3132712543,3132712546,3132712542,3132712541,3132712548,3132712540,3132712539]::bigint[])
  from special_event_pages
  where event_id = 'diwali-2026' and page_number = 1;

-- Page 2 (2×2 = 4 deals), positions 1..4 row-major:
insert into special_event_deals (page_id, "position", seed)
select id, unnest(array[1,2,3,4]), unnest(array[2525122806,2525122804,2525122803,2525122808]::bigint[])
  from special_event_pages
  where event_id = 'diwali-2026' and page_number = 2;

-- Page 3 (2×2 = 4 deals), positions 1..4 row-major:
insert into special_event_deals (page_id, "position", seed)
select id, unnest(array[1,2,3,4]), unnest(array[3838958823,3838958825,3838958821,3838958827]::bigint[])
  from special_event_pages
  where event_id = 'diwali-2026' and page_number = 3;

