-- ============================================================
-- Special Event deal seeds — auto-generated by scripts/generateEventSeeds.mjs
-- Generated: 2026-09-03T01:32:05.396Z
-- Solver: embedded JS fallback
-- Positions are row-major: position 1 = top-left, gridSize² = bottom-right.
-- Paste into: Supabase Dashboard > SQL Editor > Run
-- ============================================================

-- Event: christmas-2026 (Christmas 2026)
insert into special_events (id, title, description, starts_at, game_kind, sort_order)
values ('christmas-2026', 'Christmas 2026', 'A festive three-page collection.', '2026-12-18T00:00:00Z', 'draw-1', 10);

insert into special_event_pages (event_id, page_number, grid_size, image_path, coin_reward)
values
  ('christmas-2026', 1, 2, 'christmas-2026/page1.png', 50),
  ('christmas-2026', 2, 3, 'christmas-2026/page2.png', 100),
  ('christmas-2026', 3, 4, 'christmas-2026/page3.png', 200);

-- Page 1 (2×2 = 4 deals), positions 1..4 row-major:
insert into special_event_deals (page_id, "position", seed)
select id, unnest(array[1,2,3,4]), unnest(array[4013499603,4013499606,4013499607,4013499609]::bigint[])
  from special_event_pages
  where event_id = 'christmas-2026' and page_number = 1;

-- Page 2 (3×3 = 9 deals), positions 1..9 row-major:
insert into special_event_deals (page_id, "position", seed)
select id, unnest(array[1,2,3,4,5,6,7,8,9]), unnest(array[4254449110,4254449108,4254449111,4254449107,4254449114,4254449103,4254449116,4254449102,4254449117]::bigint[])
  from special_event_pages
  where event_id = 'christmas-2026' and page_number = 2;

-- Page 3 (4×4 = 16 deals), positions 1..16 row-major:
insert into special_event_deals (page_id, "position", seed)
select id, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]), unnest(array[3885508347,3885508348,3885508346,3885508349,3885508345,3885508350,3885508344,3885508343,3885508342,3885508341,3885508354,3885508340,3885508355,3885508356,3885508357,3885508358]::bigint[])
  from special_event_pages
  where event_id = 'christmas-2026' and page_number = 3;

